version: 2.1

jobs:
  # [ ... ALL YOUR JOB DEFINITIONS REMAIN UNCHANGED ... ]
  # The jobs section is correct and already defined above.

# --------------------------
# WORKFLOWS (Each job/sequence is a separate, independent pipeline run)
# --------------------------
workflows:
  version: 2
  
  # 1. Independent Workflow for PASS JOB
  qei-pass-pipeline:
    jobs:
      - pass-job

  # 2. Independent Workflow for FAIL JOB
  qei-fail-pipeline:
    jobs:
      - fail-job

  # 3. Independent Workflow for MULTIPLE TEST JOB
  qei-multiple-pipeline:
    jobs:
      - multiple-job

  # 4. Independent Workflow for PARENT-CHILD SEQUENCE
  qei-parent-child-pipeline:
    jobs:
      - parent-child-step1
      - parent-child-step2:
          requires:
            - parent-child-step1
  
  # 5. Full Pipeline (Optional - for running everything at once)
  #    You can still keep a single workflow to run all the above jobs together
  qei-full-pipeline:
    jobs:
      - pass-job
      - fail-job
      - multiple-job
      - parent-child-step1
      - parent-child-step2:
          requires:
            - parent-child-step1
  
  # 6. Scheduled Pipeline (Optional - Keep your original scheduled run)
  qei-scheduled-run:
    triggers:
      - schedule:
          cron: "30 6 * * 0" 
          filters:
            branches:
              only: master
    jobs:
      # This runs the full set of tests on schedule
      - pass-job
      - fail-job
      - multiple-job
      - parent-child-step1
      - parent-child-step2:
          requires:
            - parent-child-step1
